fix(cargo-safe-tool): panic if rustc panics
The application panicked (crashed).
Message:  Property { property: "UserProperty" } is not discharged
Location: src/analyze_hir/visit.rs:62

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

thread 'main' panicked at src/bin/cargo-safe-tool.rs:38:9:
[error] /home/gh-zjp-CN/tag-std/demo/rustc_driver/target/debug/safe-tool: args=[
    "--crate-name",
    "demo",
    "--edition=2024",
    "src/main.rs",
    "--error-format=json",
    "--json=diagnostic-rendered-ansi,artifacts,future-incompat",
    "--diagnostic-width=142",
    "--crate-type",
    "bin",
    "--emit=dep-info,link",
    "-C",
    "embed-bitcode=no",
    "-C",
    "debuginfo=2",
    "--check-cfg",
    "--crate-type",
    "bin",
    "--emit=dep-info,link",
    "-C",
    "embed-bitcode=no",
    "-C",
    "debuginfo=2",
    "--check-cfg",
    "cfg(docsrs,test)",
    "--check-cfg",
    "cfg(feature, values())",
    "-C",
    "metadata=0e38ac90a108eb6c",
    "-C",
    "extra-filename=-692d58835c874b29",
    "--out-dir",
    "/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps",
    "-C",
    "incremental=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/incremental",
    "-L",
    "dependency=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps",
    "--extern",
    "demo=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps/libdemo-253de311078d440f.rlib",
    "--extern",
    "safety_tool_lib=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps/libsafety_tool_lib-e86bedf8133660d6.rlib",
] vars=[]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `demo` (bin "demo")

Caused by:
  process didn't exit successfully: `/home/gh-zjp-CN/tag-std/demo/rustc_driver/target/debug/cargo-safe-tool --crate-name demo --edition=2024 s
rc/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=142 --crate-type bin --emit=dep-in
fo,link -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=0e38ac90a108eb6c -C
 extra-filename=-692d58835c874b29 --out-dir /home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps -C incremental=/home/gh-zj
p-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/incremental -L dependency=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target
/debug/deps --extern demo=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps/libdemo-253de311078d440f.rlib --extern safet
y_tool_lib=/home/gh-zjp-CN/tag-std/demo/rustc_driver/tests/basic/target/debug/deps/libsafety_tool_lib-e86bedf8133660d6.rlib` (exit status: 101
)

thread 'main' panicked at src/bin/cargo-safe-tool.rs:38:9:
[error] cargo: args=[
    "build",
] vars=[("RUSTC", "/home/gh-zjp-CN/tag-std/demo/rustc_driver/target/debug/cargo-safe-tool"), ("WRAPPER", "1")]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace